name: 'Cleanup Pulumi Stacks'
description: 'Automatically cleanup development/preview stacks in a Pulumi project'
author: 'John Brunton'
branding:
  icon: trash-2
  color: green
inputs:
  working-directory:
    description: Working directory of your Pulumi project
    default: '.'
  config:
    required: false
    description: Cleanup policies to apply
  config_file:
    required: false
    description: Path to a policies file
    default: 'cleanup-config.yml'
  preview:
    required: false
    description: When set to true, logs what what the action would do but doesn\'t destroy and stacks
    default: 'true'
  verbose:
    required: false
    description: Outputs detailed logs regarding the checks for each stack
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
